[project]
name = "pid-controller-for-tcp-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "simple-pid>=2.0.1",
]
